### ISSUE TITLE
Method not found: 'Void Telegram.Bot.TelegramBotClient..ctor

### ISSUE THREAD

**Issue by R00iBaard** [MajMcCloud/TelegramBotFramework#12]
Hi,

Thanks so much for this project, Im really looking forward to migrating to this from the "low level" telegram.bot - hopefully it provides us with more flexibility. I am running into the following issue during the execution of the AsyncFormUpdates project 

`bot = new TelegramBotBase.BotBase<forms.Start>(apiKey);
`

I am getting the following error. Using this nuget package within my application I am getting the same error.

![image](https://user-images.githubusercontent.com/11412240/127319107-1e0c5521-ebb4-41f6-94b7-ac495a44023c.png)

**Comment by MajMcCloud** [comment]
Hey!

thanks for your feedback.
Could it be that your running it with the latest Telegram Bot Framework version (>=16) ?
This is not supported in the current nuget package. You have to use something like 15 for now.

Im working already on an update, this will come the next days with some additional features.

**Comment by R00iBaard** [comment]
Thanks so much for your feedback. You are 100% correct. Really appreciate it

**Comment by MajMcCloud** [comment]
Hey!

check out our new version, it should help and you should be able to use that latest version of the original framework!

Warm regards
Florian Dahn

**Comment by R00iBaard** [comment]
Hope it's ok to re open this. 

I see after updating Telegram.Bot to version 22.2, a similar error gets logged during BotBaseBuilder.Create() (running TelegramBotBase 6.6.0)....

Method not found: 'Void Telegram.Bot.TelegramBotClient..ctor(System.String, System.Net.Http.HttpClient)'.
at TelegramBotBase.Base.MessageClient..ctor(String apiKey)
   at TelegramBotBase.Builder.BotBaseBuilder.NoProxy(Boolean throwPendingUpdates, Int32 timeoutInSeconds)

**Comment by MajMcCloud** [comment]
Hey, 
please use the latest preview version 7.0, cause that's the only version which should work with the latest Telegram Bot library of version 22.0

Cheers

**Comment by R00iBaard** [comment]
Many thanks!
